# Default depth estimation configuration

# Training setup
n_ensemble_models: 5
n_variance_models: 1
n_epochs: 64
eval_freq: 5
batch_size: 32
pair_models: true

# Dataset configuration
dataset_name: simple_depth
dataset_attrs:
  dataset_path: null  # Will use default path in DepthDataset
  shuffle: true
  noise_level: 0.1
  train_split: 0.1
  augment: false
  augmentations:
    colorjitter: false
    gaussianblur: false
    grayscale: false
    flip: false
    gaussian_noise: false

# Model classes
mean_model_class: UNet
variance_model_class: UNet

# Mean model parameters
mean_model_params:
  in_channels: 3
  out_channels: [1]
  drop_prob: 0.2

# Mean model training parameters
mean_optimizer_type: Adam
mean_optimizer_params:
  lr: 5.0e-5
  weight_decay: 1.0e-5
mean_scheduler_type: null
mean_scheduler_params: null
mean_predictor: pred_mse
mean_criterion: crit_edge_aware_mse

# Variance model parameters
variance_framework: bayescap
variance_model_params:
  in_channels: 1
  out_channels: [1, 1, 1]
  drop_prob: 0.3

variance_predictor: pred_bayescap
variance_criterion: crit_bayescap

# Variance model training parameters
variance_optimizer_type: AdamW
variance_optimizer_params:
  lr: 5.0e-5
  weight_decay: 1.0e-4
variance_scheduler_type: CosineAnnealingLR
variance_scheduler_params:
  T_max: 150
